### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by KpoJLuK32** [256dev/litecrm#2]
В заказах 
Исполнитель вместо клиента
_resources/views/main/order/showAllblade.php_ **_22 строка_**

При добавлении скидки после того как нажать по input и нажать enter вылетает ошибка 404, кнопка "изменить" работает

**Comment by student055** [comment]
В заголовке таблице изспраленно коректное описание.
Отключена обработка Enter в модальном окне с добавлением скидки.

**Comment by student055** [comment]
В заголовке таблице изспраленно коректное описание.
Отключена обработка Enter в модальном окне с добавлением скидки.

**Comment by student055** [comment]
В заголовке таблице изспраленно коректное описание.
Отключена обработка Enter в модальном окне с добавлением скидки.

**Comment by student055** [comment]
Ошибки исправлены.
